CREATE TABLE auditoriums
(
    id         UUID NOT NULL,
    theater_id UUID,
    name       VARCHAR(100),
    capacity   INTEGER,
    CONSTRAINT pk_auditoriums PRIMARY KEY (id)
);

CREATE TABLE bookings
(
    id         UUID         NOT NULL,
    user_id    UUID         NOT NULL,
    seat_id    UUID         NOT NULL,
    status     VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE images
(
    id           UUID         NOT NULL,
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    image_data   OID          NOT NULL,
    file_size    BIGINT       NOT NULL,
    image_order  INTEGER,
    resource_id  UUID         NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE movies
(
    id          UUID         NOT NULL,
    title       VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    duration    FLOAT        NOT NULL,
    genre       VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE screenings
(
    id            UUID NOT NULL,
    auditorium_id UUID,
    movie_id      UUID,
    start_time    TIMESTAMP WITHOUT TIME ZONE,
    end_time      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_screenings PRIMARY KEY (id)
);

CREATE TABLE seats
(
    id           UUID NOT NULL,
    screening_id UUID,
    seat_number  INTEGER,
    is_available BOOLEAN,
    version      VARCHAR(255),
    CONSTRAINT pk_seats PRIMARY KEY (id)
);

CREATE TABLE system_roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_system_roles PRIMARY KEY (id)
);

CREATE TABLE theaters
(
    id       UUID         NOT NULL,
    name     VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    CONSTRAINT pk_theaters PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id UUID   NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id           UUID         NOT NULL,
    username     VARCHAR(150) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    password     VARCHAR(255),
    created_date date,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE INDEX idx_resource_id ON images (resource_id);

ALTER TABLE auditoriums
    ADD CONSTRAINT FK_AUDITORIUMS_ON_THEATER FOREIGN KEY (theater_id) REFERENCES theaters (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_SEAT FOREIGN KEY (seat_id) REFERENCES seats (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE screenings
    ADD CONSTRAINT FK_SCREENINGS_ON_AUDITORIUM FOREIGN KEY (auditorium_id) REFERENCES auditoriums (id);

ALTER TABLE screenings
    ADD CONSTRAINT FK_SCREENINGS_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screenings (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES system_roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);