CREATE TABLE auditoriums
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    theater_id BIGINT,
    name       VARCHAR(100),
    capacity   INTEGER,
    CONSTRAINT pk_auditoriums PRIMARY KEY (id)
);

CREATE TABLE bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    seat_id    BIGINT                                  NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE movies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255),
    poster_image VARCHAR(255),
    duration     INTEGER,
    genre        VARCHAR(255),
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE screenings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    auditorium_id BIGINT,
    movie_id      BIGINT,
    start_time    TIMESTAMP WITHOUT TIME ZONE,
    end_time      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_screenings PRIMARY KEY (id)
);

CREATE TABLE seats
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    screening_id BIGINT,
    seat_number  INTEGER,
    is_available BOOLEAN,
    version      VARCHAR(255),
    CONSTRAINT pk_seats PRIMARY KEY (id)
);

CREATE TABLE system_roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_system_roles PRIMARY KEY (id)
);

CREATE TABLE theaters
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    location VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_theaters PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(150)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255),
    created_date date,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE auditoriums
    ADD CONSTRAINT FK_AUDITORIUMS_ON_THEATER FOREIGN KEY (theater_id) REFERENCES theaters (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_SEAT FOREIGN KEY (seat_id) REFERENCES seats (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE screenings
    ADD CONSTRAINT FK_SCREENINGS_ON_AUDITORIUM FOREIGN KEY (auditorium_id) REFERENCES auditoriums (id);

ALTER TABLE screenings
    ADD CONSTRAINT FK_SCREENINGS_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

ALTER TABLE seats
    ADD CONSTRAINT FK_SEATS_ON_SCREENING FOREIGN KEY (screening_id) REFERENCES screenings (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES system_roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);